---
title: "Biostat 212a Homework 5"
subtitle: "Due Mar 11, 2024 @ 11:59PM"
author: "Jiyin (Jenny) Zhang, UID: 606331859"
date: today
format:
  html:
    theme: cosmo
    embed-resources: true
    number-sections: true
    toc: true
    toc-depth: 4
    toc-location: left
    code-fold: false
engine: knitr
knitr:
  opts_chunk: 
    fig.align: 'center'
    # fig.width: 6
    # fig.height: 4
    message: FALSE
    cache: false
---

## ISL Exercise 9.7.1 (10pts)

This problem involves hyperplanes in two dimensions.

__(a)__ Sketch the hyperplane 1 + 3X1 − X2 = 0. Indicate the set of points for 
which $1+3X_1 −X_2 > 0$, as well as the set of points for which 
$1 + 3X_1 − X_2 < 0$.

__(b)__ On the same plot, sketch the hyperplane $−2 + X_1 + 2X_2 = 0$. Indicate 
the set of points for which $−2 + X_1 + 2X_2 > 0$, as well as the set of points 
for which $−2+X_1+2X_2 <0$.

**Answer:**

Plotting the line:

$$
1 + 3X_1 − X_2 = 0 \Leftrightarrow X_2 = 1 + 3X_1

$$
Rearranging for $X_2$ makes it clear which side of the hyperplane is which:

$$
1 + 3X_1 − X_2 > 0 \Leftrightarrow X_2 < 1 + 3X_1 \\

1 + 3X_1 − X_2 < 0 \Leftrightarrow X_2 > 1 + 3X_1

$$

Plotting another line:

$$
−2 + X_1 + 2X_2 = 0 \Leftrightarrow X_2 = 1 - \frac{1}{2}X_1

$$
Rearranging for $X_2$ makes it clear which side of the hyperplane is which:

$$
−2 + X_1 + 2X_2 > 0 \Leftrightarrow  X_2 > 1 - \frac{1}{2}X_1 \\

−2 + X_1 + 2X_2 < 0 \Leftrightarrow X_2 < 1 - \frac{1}{2}X_1

$$

```{r}
library(ggplot2)

# line in a)
df <- data.frame(x1 = -10:10, x2 = 1 + 3 * (-10:10))
# line in b)
df2 <- data.frame(x1 = -10:10, x2 = 1 - 1/2 * (-10:10))

ggplot(df, aes(x = x1, y = x2)) +
  geom_line(color = "blue") + 
  # Add math expressions
  geom_text(aes(x = 0, y = -20), label ="paste('1 + 3', italic(X[1]), ' - ', italic(X[2]), ' > 0')", color = "blue", parse = TRUE) + 
  geom_text(aes(x = 0, y = 20), label = "paste('1 + 3', italic(X[1]), ' - ', italic(X[2]), ' < 0')", color = "blue", parse = TRUE) + 
  theme_minimal() +
  labs(x = "X1", y = "X2") +
  geom_line(data = df2, aes(x = x1, y = x2), color = "red") +
  geom_text(data = df2, aes(x = -5, y = 0), label = "paste('-2 + ', italic(X[1]), ' + 2', italic(X[2]), ' < 0')", color = "red", parse = TRUE) +
  geom_text(data = df2, aes(x = 7, y = 0), label = "paste('-2 + ', italic(X[1]), ' + 2', italic(X[2]), ' > 0')", color = "red", parse = TRUE) 
  
  
```




## ISL Exercise 9.7.2 (10pts)

We have seen that in p = 2 dimensions, a linear decision boundary takes the form 
$\beta_0 +\beta_1X_1 +\beta_2X_2 = 0$. We now investigate a non-linear decision 
boundary.

__(a)__ Sketch the curve

$$

$$

## Support vector machines (SVMs) on the `Carseats` data set (30pts)

Follow the machine learning workflow to train support vector classifier (same as SVM with linear kernel), SVM with polynomial kernel (tune the degree and regularization parameter $C$), and SVM with radial kernel (tune the scale parameter $\gamma$ and regularization parameter $C$) for classifying `Sales<=8` versus `Sales>8`. Use the same seed as in your HW4 for the initial test/train split and compare the final test AUC and accuracy to those methods you tried in HW4.

## Bonus (10pts)

Let
$$
f(X) = \beta_0 + \beta_1 X_1 + \cdots + \beta_p X_p = \beta_0 + \beta^T X. 
$$
Then $f(X)=0$ defines a hyperplane in $\mathbb{R}^p$. Show that $f(x)$ is proportional to the signed distance of a point $x$ to the hyperplane $f(X) = 0$. 
